// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/moaiohio-redesign/Atlas.tsx": () => import("../components/mockups/moaiohio-redesign/Atlas.tsx"),
  "./components/mockups/moaiohio-redesign/Current.tsx": () => import("../components/mockups/moaiohio-redesign/Current.tsx"),
  "./components/mockups/moaiohio-redesign/Playful.tsx": () => import("../components/mockups/moaiohio-redesign/Playful.tsx"),
  "./components/mockups/moaiohio-redesign/Sculpture.tsx": () => import("../components/mockups/moaiohio-redesign/Sculpture.tsx"),
  "./components/mockups/moaiohio-redesign/Sunlit.tsx": () => import("../components/mockups/moaiohio-redesign/Sunlit.tsx")
};
